baseURL: "https://eshanepicfighter.github.io/Eshanepicfighter/"
title: Esh's Blog
paginate: 5
theme: "PaperMod"

outputs:
    home:
        - HTML
        - RSS
        - JSON 

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: About
                  url: about/
                  weight: 10
                - name: Donate
                  url: donate/
                  weight: 10

params:
    editPost:
        URL: "https://github.com/Eshanepicfighter/Eshanepicfighter/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link	

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

    description: "Esh's Blog"
    author: Esh


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "https://user-images.githubusercontent.com/79593316/127756718-008cdf7e-42d5-447f-9178-cef608d3860b.PNG"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: About
              url: about
            - name: Archive
              url: archives

    homeInfoParams:
        Title: "Esh's Blog"
        Content: >
            The home of ideas, thoughts, and rants from the creator of <a href="https://eshanepicfighter.github.io/PhotosForFree">PhotosForFree</a>
    socialIcons:
        - name: github
          url: "https://github.com/Eshanepicfighter/Eshanepicfighter"
        - name: RSS Feed
          url: "index.xml"


taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
